#ADVANCED CONFIG
#I do not suggest modifying these settings unless you know what you are doing!

#Prompt to give OpenAI
openai-prompt: "Respond as a Discord user called {botname}. They are {personality}.\n\n{sendername}: {message}"

#Placeholders:
#{botname}
#{sendername}
#{personality}
#{message}

#GPT-3 stop words
openai-stop: " {sendername}:"

#OpenAI token limit
token-limit: 120

#Input string length limit
length-limit: 200

#What to do with messages that are too long
#Clip - Clip message
#Ignore - Ignore message
#Weird - Send a weird string of text (DOES NOT USE OPENAI)
#Use "clip", "ignore", or "weird"
lengthy-messages-action: ignore

#Attempt to use messages the bot has previously sent instead of generating a new one
use-old-messages: False


#Attempt to filter profanity from the AI
filter-profanity: True

#Make the AI spell badly/have bad grammar
bad-spelling: False


#Enable if you want to speak directly to the AI with no context
#WARNING: Socially awkward/NSFW
no-prompt: False

#Attempt to separate out the actual response
#NOTE: Does not work well when no-prompt is set to True
parse-output: True

#Cache the config during runtime (CANNOT BE CHANGED DURING RUNTIME)
#Enable if you don't change settings while Trollbot is running
cache-config: True

#Toggle debug logging (CANNOT BE CHANGED DURING RUNTIME)
debug: False

#Exclude certain modules from debug logging (CANNOT BE CHANGED DURING RUNTIME)
debug-exclude:
- none

#List of modules that can be excluded:
#- start_cmd
#- trollbot_core
#- trollbot_config
#- trollbot_discord_ai
#- trollbot_discord_profile
#- trollbot_commands
#- oshla_utils
