#Bot prefix (set to "none" to respond to all messages)
bot-prefix: none

#Chance the bot will respond to the message (set to 1 to respond to all messages)
response-chance: 1

#Wait for a random period of time before sending a message?
send-wait: True

#AI Personalitys
personalities:
- friendly, and they only respond in Unicode emojis
- clever, and friendly

personality: 2


#Make the bot join a voice channel when mentioned and use Uberduck.ai to generate a voice
join-voice: False

#Users to ignore
ignored-users:
#- Discord user ID here
