#!/bin/bash
case $1 in
start)
cd trollbot
source trollbot_env/bin/activate
python3 start_cmd.py
;;
install)
echo Installing Trollbot...
cd trollbot
python3 -m venv trollbot_env
source trollbot_env/bin/activate
pip3 install -r requirements.txt
;;
*)
echo "Unknown operation. Use 'install' or 'start'"
;;
esac